<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Daftar Akun</name>
   <tag></tag>
   <elementGuidId>df00887a-f3fc-4300-9ea8-db073a10611f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='safe-area']/div[2]/div/div/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.header_2xOrt.mx-auto.text-color-gray-dark</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>1acbdb50-f653-4595-bc67-a582a46b0b68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header_2xOrt mx-auto text-color-gray-dark</value>
      <webElementGuid>171f513a-328c-4b28-8ea7-f4ad30353d7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daftar Akun</value>
      <webElementGuid>23064e0e-ac12-4b47-8878-70162da3e950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;safe-area&quot;)/div[2]/div[@class=&quot;superapp-container AppHeader_container__2IvQP&quot;]/div[@class=&quot;AppHeader_card__3C4Pk background-primary&quot;]/h1[@class=&quot;header_2xOrt mx-auto text-color-gray-dark&quot;]</value>
      <webElementGuid>f2c89f9b-a6b6-46cc-ab3d-6f76916ae66a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='safe-area']/div[2]/div/div/h1</value>
      <webElementGuid>afbcbb24-c8a5-4545-8c19-acd351f9707d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/preceding::h1[1]</value>
      <webElementGuid>916a9163-26bd-4ddd-a852-8e57b303963b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No. Handphone'])[1]/preceding::h1[1]</value>
      <webElementGuid>596b8af6-c064-4c7a-8413-32c0ea695300</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Daftar Akun']/parent::*</value>
      <webElementGuid>1b908a13-79b0-4854-ba11-18fd806d9882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>f0419ea0-6c3a-40c3-8e70-d2636d981684</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Daftar Akun' or . = 'Daftar Akun')]</value>
      <webElementGuid>ddff4052-b22b-4e4b-9841-637f66348218</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
