<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_KabupatenKota_cityAndProvince</name>
   <tag></tag>
   <elementGuidId>661295c3-5533-40a4-b036-b4fdac6bdafd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cityAndProvince']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cityAndProvince</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>79e10aea-5db6-46f4-9f7c-634e7680824c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a45d059a-efa2-45fe-b339-f08b4fb56d76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>autocomplete__field_vc5UL</value>
      <webElementGuid>3c1a2026-eb18-40b4-b6fb-ea4f32085809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cityAndProvince</value>
      <webElementGuid>f384a1a6-7043-4c59-96d7-4d28630430c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cityAndProvince</value>
      <webElementGuid>c7f1f8c3-56f9-4a08-bb79-0c3b68b44877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pilih Kabupaten/Kota</value>
      <webElementGuid>bea58c61-7b86-4feb-9597-cf854f9cf92a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>843c53c1-71b3-4922-86e8-15f9183cf9d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cityAndProvince&quot;)</value>
      <webElementGuid>ebb37a85-a507-45ef-98e8-85e9fcd3f819</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cityAndProvince']</value>
      <webElementGuid>79d9dda6-92e9-407e-bb12-aacc5e6cb0cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='safe-area']/div[2]/div[2]/div/div[6]/div/input</value>
      <webElementGuid>06d16a56-a94a-4681-80f8-7028b3fd6182</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>0eb3615c-581b-46f7-80da-699b5e4a9ebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cityAndProvince' and @name = 'cityAndProvince' and @placeholder = 'Pilih Kabupaten/Kota' and @type = 'text']</value>
      <webElementGuid>97f71a28-709d-48e0-8972-1a8ad6703c42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
